server:
  port: 8989
#  servlet:
#    context-path: /sms

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sms?useUnicode=true&characterEncoding=utf-8&useSSL=FALSE&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        dialect:
#          org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false

white:
  list:
    uris:
      - /authentication
      - /login
      - /logout
      - /css/**
      - /js/**
      - /images/**
      - /plugins/**
